services:

  mongodb:
    container_name: spellingbee_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./VOLUMES/mongodb_data:/data/db
      - ./VOLUMES/mongodb_configdb:/data/configdb

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:?Your .env file must have a MONGO_ROOT_USERNAME variable}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:?Your .env file must have a MONGO_ROOT_PASSWORD variable}
      - MONGO_INITDB_DATABASE=spellingbee

    restart: unless-stopped



  spellingbee_streamlit:
    container_name: SpellingBee

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${STREAMLIT_PORT:?Your .env file must have a STREAMLIT_PORT variable}:8501"

    volumes:
      - ./src:/app/src
      - ./auth.yaml:/app/auth.yaml

    environment:
      # Avoid output buffering; this line ensures that print() statements are sent directly to the terminal
      - PYTHONUNBUFFERED=1
      # Set DEBUG to 1 (in your .env file) if you want to see the logs
      - DEBUG=${DEBUG}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:?Your .env file must have a MONGO_ROOT_USERNAME variable}:${MONGO_ROOT_PASSWORD:?Your .env file must have a MONGO_ROOT_PASSWORD variable}@mongodb:27017/spellingbee?authSource=admin

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${STREAMLIT_PORT}/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: unless-stopped

    command: ["streamlit", "run", "run_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]